### ISSUE TITLE
Default constructors and dimension

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#13]
I would love to see default constructors like `Euclidean(n)` also for the Sphere. Shall we do that in general?

And I noticed that `dimension` might be something different than I thought. I thought it would be the manifold dimension, but since Sphere(2) (or its longer version `Sphere((3,))` is a 2d manifold and `dimension` would return 3, what is dimension for then? Could we either change that to return 2 (for the example just mentioned) or also provide a `manifold_dimension`?

**Comment by sdaxen** [comment]
> I would love to see default constructors like Euclidean(n) also for the Sphere. Shall we do that in general?

I like this idea

> And I noticed that dimension might be something different than I thought. I thought it would be the manifold dimension, but since Sphere(2) (or its longer version Sphere((3,)) is a 2d manifold and dimension would return 3, what is dimension for then? Could we either change that to return 2 (for the example just mentioned) or also provide a manifold_dimension?

In my mind, `dimension` refers to the dimension of the manifold, not the dimension of a specific set of coordinates (which may have more dimensions, e.g. for embedded manifolds).

So in my mind `dimension(Sphere(2))` should return 2. I also prefer this implementation, since it lets us dispatch on sphere dimension where useful

```julia
struct Sphere{N} <: Manifold end
Sphere(n::Int) = Sphere{n}()
dimension(::Sphere{N}) where {N} = N
```

**Comment by kellertuer** [comment]
I am nearly with your code, just that – since for now internally the shape is stored, `Sphere(n)` has to be `Sphere( (n-1,) )` and dimension (which is now the sum of shapes) is – I don't know what, since I've never seen spheres with shapes that are more than one dimension long, and I am not sure what that's meant to represent (since for Power we have a decorator, hopefully soon).

**Comment by mateuszbaran** [comment]
I also don't see a reason use shapes with more than one dimension for a sphere. I like the definition by @sdaxen .

**Comment by sdaxen** [comment]
Currently, `manifold_dimension` returns the dimension of the manifold, but there are related quantities we might be interested in. The first is the size of the default representation as a vector or matrix. The second is the dimension of the ambient space for embedded manifolds. For the first, we could return this with something like `representation_size`, analogous to `Base.size`. For the second, we could use a multi-parameter trait `IsEmbedded` to mark the manifolds that have a default embedding and designate the corresponding Euclidean space (similar to `HasMetric`). The suitable default for `representation_size` for manifolds that are embedded would be to return the `representation_size` for the ambient space.

**Comment by mateuszbaran** [comment]
`representation_size` will be necessary for `Product` and `Power` manifolds, so we really need this function. Dimension of the ambient space is just a composition of a "get the ambient space" function (which I think we should have for embedded manifolds) and `manifold_dimension`.

**Comment by sdaxen** [comment]
I gave it some more thought, and I don't think the multiparameter trait approach will work for us here. For example, for `Sphere`, we would ideally do something like

```julia
@traitdef IsEmbeddedManifold{M,A}
SimpleTraits.trait(::Type{IsEmbeddedManifold{M,A}}) where {N,M<:Sphere{N},A<:Euclidean{Tuple{N+1}}} = IsEmbeddedManifold{M,A}
``` 
The latter statement is the [advanced form](https://github.com/mauro3/SimpleTraits.jl#advanced-features) of what `@traitimpl` does. However, from what I understand, Julia doesn't allow this syntax because `N` is a `TypeVar`, so we get the message `MethodError: no method matching +(::TypeVar, ::Int64)`.

An alternative is something like

```julia
@traitdef IsEmbeddedManifold{M}
@traitfn ambient(M::::IsEmbeddedManifold) = error("ambient not implemented")
@traitimpl IsEmbeddedManifold{Sphere}
ambient(::Sphere{N}) where {N} = Euclidean(N + 1)
```

which lets us dispatch on embedded manifolds if necessary and also define the ambient manifold. Thoughts?

**Comment by mateuszbaran** [comment]
The only way I know to do the first thing in Julia would be to use type-level natural numbers like this:
```julia
abstract type TypeNumber end
struct Zero <: TypeNumber end
struct Succ{N <: TypeNumber} <: TypeNumber end

f(::Type{N}, ::Type{N}) where N = "same"
f(::Type{N}, ::Type{Succ{N}}) where N = "+1"
f(::Type{N}, ::Type{Succ{Succ{N}}}) where N = "+2"
```
but I think we would quickly break the type system this way. The alternative looks like a better solution.

**Comment by kellertuer** [comment]
I also thought about this. The `EmbeddedManifold` is nice, but then we have only exactly one embedding. That might also be fine, since we can distingiush these with different parametrisation, _if_ you can do different embeddings. Further, for `IsEmbeddedManifold` we can also define
`embedding_dimension` (or `ambient_dimension`) to get the dimension of the space, the manifold is embedded into. The next good thing with this trait (but one could also do a decorator again) is, that one can easily define `project` and `embed` this way.

I was initially thinking that all this would couple two manifolds (the ambient one and the sub manifold one), but that might also be a little too complicated.

**Comment by sdaxen** [comment]
My idea for `IsEmbeddedManifold` above simply marks manifolds whose default parameterization is in embedded coordinates (and probably whose default metric is inherited from the embedding). Since there will only be one set of default (undecorated) coordinates per manifold, this eliminates the ambiguity. `ambient` would return the ambient manifold, which provides some coupling. But all this really gives us is sizes and dimensions, which we could always implement directly.

Perhaps we should revisit this when we are implementing maps, since we may be able to use the same machinery to specify a variety of derived manifolds.

**Comment by sethaxen** [comment]
The main topic of this thread has been implemented, and other more recent discussion of implementing embedded manifolds can continue in https://github.com/JuliaNLSolvers/Manifolds.jl/issues/77 or another issue.
