### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaNLSolvers/Manifolds.jl#19]
Most Julia packages have project names that end with ".jl" but ManifoldMuseum does not. Do you think it should be renamed?

**Comment by sdaxen** [comment]
I think so. As I mentioned in https://github.com/JuliaNLSolvers/ManifoldMuseum/issues/4#issuecomment-499638109, I favor something like `Manifold.jl`, since we're providing a general-purpose interface for working with manifolds, not just a "museum" of manifold implementations.

**Comment by dkarrasch** [comment]
Yes, or something like `ManifoldsBase.jl`, to indicate that this is the base package for "everything" related to manifolds, similar to `DiffEqBase.jl` or `OptimBase.jl`?

**Comment by kellertuer** [comment]
I think the `MainfoldMuseum` was thought as something building upon `Manifold(s).jl`, but I am even in favour of keeping the interface and a certain (well documented) set of (easy, useful, available) manifolds that are of interest to a broad audience (again avoiding that everyone implements them again and again). With a set of manifolds it would even exceed the base, maybe?

So I would call it either
* `Manifolds.jl` not specifying that it also includes the base, but this name reflects that you get manifolds
* `Manifold(s)Base.jl` (maybe without the `s` since the base would be one for ***a*** manifold
* splitting it into `ManifoldBase.jl` just the interface and our old idea of then a `ManifoldMuseum.jl`

I am actually in favour of the first, since with manifolds its more than a base.

**Comment by mateuszbaran** [comment]
I wouldn't split this package into two yet, there is no clear purpose for that and it's harder to coordinate two repositories than working with one. Otherwise, I like the name `Manifold(s).jl`.

**Comment by kellertuer** [comment]
I am in favour of the plural, since we do not only provide one type of (Riemannian) manifold.

**Comment by sdaxen** [comment]
I'm happy with `Manifolds.jl` too. Let's change it. :)

**Comment by dkarrasch** [comment]
Sounds good. I think it's certainly not misleading to call it `Manifolds.jl` and have both the generic interface and a couple of standard manifolds already implemented here.

**Comment by mateuszbaran** [comment]
So, how do we change the name? @antoine-levitt has created this one and already has a package called `Manifolds.jl`: https://github.com/antoine-levitt/Manifolds.jl .

**Comment by antoine-levitt** [comment]
Done! I think you guys should be able to do that too? At least I gave you the highest permission I could.

**Comment by mateuszbaran** [comment]
Thanks, great! I didn't think about checking if I can change the name but indeed I have such option.

**Comment by kellertuer** [comment]
Yes, @antoine-levitt , I think we all could've changed the name, at least I have the rights to do that, but I was travelling today – so great to have a new nice name :)
