### ISSUE TITLE
Behavior of `is_manifold_point`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaNLSolvers/Manifolds.jl#24]
As suggested here: https://github.com/JuliaNLSolvers/Manifolds.jl/pull/18#discussion_r297415302 we should have two different functions: one for testing whether a point belongs to a manifold that returns `true` or `false` and the other one that throws an error when the point does not belong to the manifold. The first one can be generically implemented using the second one, with a `try` block. I'm not sure though how to name these functions.

**Comment by sdaxen** [comment]
Maybe something like `is_manifold_point` for the function that returns a `Bool` and `check_manifold_point` for the function that uses it.

**Comment by kellertuer** [comment]
For me, both also have a slightly different goal: while `is_manifold_point` should just (maybe even with goal performance) return `true or `false`, the other (maybe also `validate_manifold_point`?) should provide a long error message that tries to return, _why_ it is not a point, for example for an Sphere point because its in the wrong space (Rn+2 instead of Rn+1) or its not unit...
So it might only be an idea for a default fallback to do the _is_ case with a try catch. I would not recommend to do the other way around (use _is_ to do _check_/_validate_), since just  ´false` would not provide any information.

Since it should throw then an error anyways (and there is a "non-erroring version“) I would also not care about performance for the `check`/`validate`/`whatevernamewefind_`.

**Comment by kellertuer** [comment]
I think this is resolved with `ManifoldsBase.jl` in version 0.2.0 and can hence be closed?

**Comment by mateuszbaran** [comment]
Technically merging #46 will solve it in this repository but yes, it's almost done.
