### ISSUE TITLE
Naming Scheme(s)

### ISSUE THREAD

**Issue by kellertuer** [JuliaNLSolvers/Manifolds.jl#4]
Since we are looking at so many interesting aspects, maybe its even better to call this package `Manifold.jl` and do the `ManifoldMuseum.jl` later as an accompanying package of examples (collection o formulae etc) to the interface?

Further – this issei's is meant to discuss a consistent naming scheme. I started with fearing that point and vector might be too general and introduce too many naming conflicts, so in `Manopt.jl` I opted for `MPoint` and `TVector` (first MTVector, but you always get confused in discussions whether that's an empty one ;)). with `TVector` one could then go on and use `CoTVector`,...

How should we then call specific subtypes?

Furthermore, how do we call manifolds?
`Sphere` is nice `Symmetric` might mean `SymmetricMatrices` but always taking full names right be a little long, so `SymmetricPositiveDefiniteMatrices` for example, especially if we intrdoduce some further subtypes.

So please collect ideas for a consistent scheme to name all these in an interface.

**Comment by sdaxen** [comment]
I like the idea of `Manifold.jl` or `ManifoldBase.jl` for the general interface and something like `ManifoldMuseum.jl` or `Manifolds.jl`, respectively for a collection of common manifolds.

`TVector` and `CoTVector` make sense. `MPoint` I guess depends on whether we're describing an abstract point or a set of coordinates. See https://github.com/JuliaNLSolvers/ManifoldMuseum/issues/6.

I don't have strong opinions on naming schemes. If we go with a Lie group interface like that given in https://github.com/JuliaNLSolvers/ManifoldMuseum/issues/1#issuecomment-499378913, I favor choosing manifold names that are descriptive but don't steal the common group name or are ambiguous. (e.g. `RotationMatrices` instead of `Rotations`). For groups like `SpecialOrthogonalGroup`, I favor using the long name and providing an abbreviated form.

For variable names, I favor `m` for a manifold and `M` for its type, `x` for a point, `v` for a tangent vector, and -`to` appended to the end of a variable when it is overwritten and would otherwise be confusing.

**Comment by sdaxen** [comment]
Perhaps `dot` should be renamed to `inner` or `inner_product`, since the dot product is only one particular inner product, and here we use many different inner products.

**Comment by mateuszbaran** [comment]
Makes sense, we can use `inner` instead of `dot`.

**Comment by kellertuer** [comment]
I'm ok with that, I mainly used dot, because it's short, so inner_procduct` might be a little long, but I'm perfectly fine with `inner`.
