### ISSUE TITLE
ManifoldsBase

### ISSUE THREAD

**Issue by sethaxen** [JuliaNLSolvers/Manifolds.jl#43]
Continuing the discussion in #35, the plan is to split the core interface and the `Euclidean` manifold into a `ManifoldsBase` package that users can add as a dependency to implement their own manifolds and get basic functionality.

The question is what features constitute the core interface? My first inclination is that more or less all the functions defined in [`Manifolds.jl`](https://github.com/JuliaNLSolvers/Manifolds.jl/blob/master/src/Manifolds.jl) comprise the interface. Are there any other features that _need_ to be in there?

Since `Euclidean` will be heavily used, we'll also want to revisit it to make sure it has the most efficient defaults. If e.g. `MetricManifold` is not in `ManifoldsBase.jl`, then `Manifolds` will need to keep some `Euclidean` specializations.

In a separate issue, we should discuss whether `Euclidean` should be extended to support complex Euclidean manifolds.

**Comment by mateuszbaran** [comment]
I think we can just copy all functions defined in https://github.com/JuliaNLSolvers/Manifolds.jl/blob/master/src/Manifolds.jl and the `Euclidean` manifold (except the stuff related to distributions and maybe metric?) and see what breaks. I think it should be mostly painless.

I think what we can do is:
1. Make a new repository `ManifoldsBase.jl`.
2. Make the package with all functions and the `Euclidean` manifold.
3. Transfer the package to `JuliaNLSolvers` org.
4. Set CI up.
5. Register `ManifoldsBase.jl` (so it can be easily added as a dependency for `Manifolds.jl`)
6. Make a PR to `Manifolds.jl` that uses `ManifoldsBase.jl`.

The first real use case for `ManifoldsBase.jl` is integration with `Optim.jl` so I'd wait with this work at least until power manifold is added (since it's needed there anyway). But if you want do to it sooner, I don't see any problem with that :slightly_smiling_face: .

> In a separate issue, we should discuss whether `Euclidean` should be extended to support complex Euclidean manifolds.

Good question, I don't have any experience with complex manifolds so I don't know what would have to be done here.

> If e.g. `MetricManifold` is not in `ManifoldsBase.jl`, then `Manifolds` will need to keep some `Euclidean` specializations.

The main point about `ManifoldsBase.jl` is a low number of dependencies, so we could put there anything that doesn't require more packages than the bare minimum. That minimum is `LinearAlgebra`, `Markdown` (for docs) and probably `SimpleTraits` (if we want metric manifolds). Is there anything else required? I'm not entirely convinced about `SimpleTraits` since from what I can tell it's not really that commonly used among Julia packages and personally I'm just doing trait-based dispatch in pure Julia using THTT when I need something like that. I hope we will eventually have an officially endorsed implementation of traits :slightly_smiling_face: .

Anyway, if not having `SimpleTraits` in `ManifoldsBase` would make implementation of metric manifolds noticeably uglier, I'm OK with adding it to `ManifoldsBase`.

**Comment by sdaxen** [comment]
> The first real use case for `ManifoldsBase.jl` is integration with `Optim.jl` so I'd wait with this work at least until power manifold is added (since it's needed there anyway). But if you want do to it sooner, I don't see any problem with that 🙂 .

Happy to wait. Now that `Manifolds` isn't so slow to load, I'll just use it as a dependency for my stuff directly until we make `ManifoldsBase`.

I haven't looked in detail, but everything related to metric manifolds is fairly advanced. And we've decided that users should implement manifolds directly and then maybe associate them with a metric and maybe add new metrics, so not having them won't inconvenience anyone.

If we can, it would be good to have `ProductManifold` in there along with `PowerManifold`.

> Good question, I don't have any experience with complex manifolds so I don't know what would have to be done here.

Well, it probably won't make a difference for `Euclidean`, so long as our methods are implemented generally enough to work for real and complex, but it does affect what the dimension should be. 2x2 Euclidean real matrices have dimension 4, while for complex matrices, it has dimension 8, which is why it might be sensible to have a type option. But that's a separate issue I can create another issue for.

**Comment by mateuszbaran** [comment]
> I haven't looked in detail, but everything related to metric manifolds is fairly advanced. And we've decided that users should implement manifolds directly and then maybe associate them with a metric and maybe add new metrics, so not having them won't inconvenience anyone.

OK, that's reasonable.

> If we can, it would be good to have `ProductManifold` in there along with `PowerManifold`.

I'm not totally sure about it. It would cause additional dependencies (`StaticArrays`, `HybridArrays`). We can always add them later to `ManifoldsBase.jl`

> Well, it probably won't make a difference for `Euclidean`, so long as our methods are implemented generally enough to work for real and complex, but it does affect what the dimension should be. 2x2 Euclidean real matrices have dimension 4, while for complex matrices, it has dimension 8, which is why it might be sensible to have a type option. But that's a separate issue I can create another issue for.

Probably complex conjugation would be needed here and there, right? But yes, it's a separate issue.

**Comment by mateuszbaran** [comment]
I've started some work on this: https://github.com/mateuszbaran/ManifoldsBase.jl . @pkofod , could you transfer that project to the JuliaNLSolvers org?

In that package I've also made some changes related to #24 (essentially splitting `is_manifold_point` and `is_tangent_vector` to three functions: one for getting error description, one for a true/false test and one that throws an error).

**Comment by pkofod** [comment]
I don't think I can, only you can move it.

**Comment by mateuszbaran** [comment]
I tried that, but apparently only org members can transfer a repository to an org. I'll transfer it to you first then.

**Comment by pkofod** [comment]
Oh that’s why. Okay we’ll do it like that

**Comment by pkofod** [comment]
Can you try again, it has expired ,. Sorry

**Comment by mateuszbaran** [comment]
Sure, I've requested transfer again 👍 .

**Comment by pkofod** [comment]
It's "here" now. Please tell me if there are any permissions you need going forward.

**Comment by mateuszbaran** [comment]
Thanks! I'd like to have write permissions there (I'm not sure if I have them now).

**Comment by kellertuer** [comment]
Thanks @pkofod for giving us a start on the `ManifoldsBase`

So I think there's some decisions left (which we might postpone to the future, see below) and we have to transition this package to be based on `ManifoldsBase`.

I think – if the have finished the design of `MetricManifold`, that that can also be moved over, since it does not require more packages and is a nice start for people who want to distinguish metric for one manifold (currently trying a first manifold in #27 – will continue there next). I also think that the Lie group (when finished) can be put there, but both `PowerManifold` and `PorductManifold` (though also easy extensions that one might have for a manifold) require too much dependencies to be put into `Base`. What do you think?

In general (as mentioned with `MetricManifold`) we should develop new manifolds and features here and if we think they should be moved to basic, move them after development. That way `Base` stays clean and simple.

Further – @mateuszbaran proposed to do _one_ documentation, namely here. So I would propose to adapt that here when doing above mentioned shift to base this package on `ManifoldsBase`, i.e. to extend/adapt the documentation to that shift accordingly.

**Comment by pkofod** [comment]
My clear preference for requirements for whether something belongs in ManifoldsBase is whether it adds dependencies or not. The way precompilation and package loading works means that dependencies of dependencies add a lot of load time, so that's important for other packages to pull in the interface but not the functionality. Then it can be opt-in at the user side if they want all the fancy stuff or just define their own manifolds.

**Comment by kellertuer** [comment]
Yes; I understand (and understood before) – so that has also to be kept in mind.

**Comment by pkofod** [comment]
> Yes; I understand (and understood before) – so that has also to be kept in mind.

I will repeat it in every discussion, haha 🤣
