### ISSUE TITLE
Add the Lie-theoretic exponential map

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaNLSolvers/Manifolds.jl#75]
As discussed in https://github.com/JuliaNLSolvers/Manifolds.jl/pull/68#discussion_r361746072

**Comment by sethaxen** [comment]
The first decision here seems to be what to call it. Options I can think of are:
- `gexp`
- `expg`
- `group_exp`
- `exp_group`

I prefer `expg` by analogy to `expm` in some languages being the matrix exponential, but I'm not thrilled with any of them.

The second decision is where to implement it. For `AdditionOperator`, it will coincide with the Riemannian exponential, and we can just forward it.
For `MultiplicationOperator`, it should default to calling `exp` for `Matrix`/`Number` inputs and otherwise be unimplemented. This would cover most textbook groups with a multiplication operation.

Analogously, I prefer `logg` (though `glog` sounds great, and now I remember I have some glög left over in the fridge).

**Comment by kellertuer** [comment]
We can of course call it `glögg` (even `gløgg` is close by), I have ö on my keyboard directly, no problem.

While `expm` is short and one knows it's the matrix Exponential, I would vote for `group_exp` for readability. Another possibility is to use the `exp(::LieGroup{M}, ::Any...)` signature maybe, where `LieGroup <: GroupManifold` or we do it with `GroupManifold`? And where I got to names, should we maybe call `GroupManifold` `LieManifold` ? For me, Lie just sounds mor familiar.

**Comment by mateuszbaran** [comment]
Sure, we can have `glögg` as an alias for Lie logarithm 😄 . As primary names, `group_exp` and `group_log` sound fine (although I also like `lie_exp` and `lie_log`).

**Comment by kellertuer** [comment]
I also like `lie_exp`, but maybe then we should really go for `LieManifold` for consistency?

**Comment by mateuszbaran** [comment]
Right, it would be inconsistent to sometimes use `Lie` and sometimes `group`. Both options, `Lie` and `group`, are fine for me.

**Comment by kellertuer** [comment]
I am fine with a decision pro-`group`, but my personal favour would be `Lie`.

**Comment by sethaxen** [comment]
I prefer `group`. Since all of our manifolds are differentiable manifolds, "Lie group" is redundant. Moreover, we can consistently use "group" everywhere without it sounding weird (e.g. `SemidirectProductGroup` but not `SemidirectProductLie`). We could maybe make it "liegroup" in some places, but then we have issues with consistency, and the names include a redundant word.

We already abbreviate some decorator names. e.g. `MetricManifold` is really `PseudoRiemannianMetricManifold`, but we shorten for convenience and document what it means.

I'm fine with `group_exp` and `group_log`.
